# Generated by Django 4.2 on 2023-04-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcenter',
            name='specialties',
        ),
        migrations.AddField(
            model_name='specialty',
            name='medical_centers',
            field=models.ManyToManyField(related_name='specialties', to='user.medicalcenter'),
        ),
    ]
