# Generated by Django 4.2 on 2023-04-04 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_medicalcenter_specialties_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcenter',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='medical_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.medicalcenter'),
        ),
        migrations.AddField(
            model_name='medicalcenter',
            name='addresses',
            field=models.ManyToManyField(related_name='centers', to='user.address'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='addresses',
            field=models.ManyToManyField(related_name='users', to='user.address'),
        ),
    ]
