# Generated by Django 4.2 on 2023-04-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_address_medical_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
