# Generated by Django 4.2 on 2023-04-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_plan_subscription_useraccount_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='boolean_value',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('boolean', 'Boolean')], max_length=10),
        ),
    ]
