# Generated by Django 4.2 on 2023-04-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customfield_boolean_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='national_id',
            field=models.PositiveIntegerField(blank=True, max_length=15, null=True),
        ),
    ]
