# Generated by Django 4.2 on 2023-04-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_useraccount_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
